name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    uses: thekevinscott/putitoutthere/.github/workflows/release.yml@v0
    permissions:
      contents: write
      id-token: write
